name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*"


jobs:
  test:
    uses: ./.github/workflows/tests.yaml

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download the build artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: wheel-${{ github.sha }}
          path: ./dist

      - name: Publish package distributions to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
