name: Test

on:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_call:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.8", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python }}

      - name: Install required packages
        shell: bash -el {0}
        run: |
          conda install conda-build hatch pytest pip -c conda-forge
          pip install .[dev]

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda list
        shell: bash -el {0}
        run: conda list

      - name: Run checks
        shell: bash -el {0}
        run: hatch env run -e test check

      - name: Run tests
        shell: bash -el {0}
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          pytest -vv
