name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # , macos-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: "3.11"

      - name: Install required packages
        shell: bash -el {0}
        run: |
          conda install conda-build hatch pytest pip -c conda-forge
          pip install .[dev]

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda list
        shell: bash -el {0}
        run: conda list

      - name: Run checks
        shell: bash -el {0}
        run: hatch env run -e test check

      - name: Run tests
        shell: bash -el {0}
        run: pytest -v
